[project]
name = "premierprojetuv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dataclasses>=0.8",
    "matplotlib>=3.10.0",
    "networkx>=3.4.2",
    "pyqt6>=6.8.0",
    "rich>=13.9.4",
]
